### ISSUE TITLE
Warning(401): Nothing known about base class 'nvinfer1::ILogger'. Ignored.

### ISSUE THREAD

**Issue by harsh-agar** [AastaNV/ChatBot#1]
Hi @AastaNV , when I try to make this on Jetson TX2, I get a warning saying:

> swig -c++ -python src/tensorNet.i
> Warning(401): Nothing known about base class 'nvinfer1::ILogger'. Ignored.
> 
> 

I am using TensorRT 3.0.0 with Cuda 8.0 and Jetpack 3.1
Any help would be highly appreciated.

Thanks

**Comment by harsh-agar** [comment]
Hey! got this working by giving appropriate paths.
So closing it.

**Comment by linhkakashi** [comment]
Hey can you explain how you fix that error. I'm facing same error right now. Thank you!
